a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espacos? ', a.isspace())
print('É um numero? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É um alfanumerico? ', a.isalnum())
print('Está em maiusculas? ', a.isupper())
